# Generated by Django 5.1.5 on 2025-02-12 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semana', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=255)),
                ('concluido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'anotação',
                'verbose_name_plural': 'anotações',
                'ordering': ['-ano', '-semana'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('periodo', models.CharField(blank=True, choices=[('am', 'Manhã'), ('pm', 'Tarde'), ('nt', 'Noite'), ('dy', 'Dia inteiro')], max_length=2, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cronograma')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.local')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade_metrica', models.CharField(choices=[('un', 'Unidade'), ('pc', 'Peça'), ('kg', 'Kilograma'), ('l', 'Litro'), ('cx', 'Caixa'), ('pt', 'Pacote'), ('kt', 'Kit'), ('ot', 'Outro')], max_length=2)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atividade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.produto')),
            ],
        ),
    ]
