# Generated by Django 5.1.5 on 2025-02-13 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.categoria'),
        ),
        migrations.AddField(
            model_name='local',
            name='icone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
