# Generated by Django 5.1.5 on 2025-02-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_atividade_categoria_local_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacao',
            options={'ordering': ['-data'], 'verbose_name': 'anotação', 'verbose_name_plural': 'anotações'},
        ),
        migrations.RemoveField(
            model_name='anotacao',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='anotacao',
            name='semana',
        ),
        migrations.AddField(
            model_name='anotacao',
            name='data',
            field=models.DateField(default='2025-02-13', help_text='Adicione qualquer data dentro da semana desejada.'),
            preserve_default=False,
        ),
    ]
